swagger: "2.0"
info:
  title: recipesvc.proto
  version: version not set
tags:
  - name: RecipeService
consumes:
  - application/json
produces:
  - application/json
paths:
  /recipe:
    post:
      summary: Adds or updates a recipe
      operationId: RecipeService_AddRecipe
      responses:
        "200":
          description: A successful response.
          schema:
            type: object
            properties: {}
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/recipesvcRecipe'
      tags:
        - RecipeService
  /recipe/{name}:
    get:
      summary: Gets a recipe by name
      operationId: RecipeService_GetRecipe
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/recipesvcRecipe'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: name
          description: Name of recipe
          in: path
          required: true
          type: string
      tags:
        - RecipeService
  /recipes:
    get:
      summary: Finds recipes based on list of ingredients
      operationId: RecipeService_FindRecipes
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/recipesvcRecipes'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: ingredients
          description: Array of ingredients to include in search
          in: query
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      tags:
        - RecipeService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  recipesvcRecipe:
    type: object
    properties:
      ingredients:
        type: array
        items:
          type: string
        title: Array of ingredients comprising the recipe
      name:
        type: string
        title: Name of recipe
    title: Recipe
  recipesvcRecipes:
    type: object
    properties:
      recipes:
        type: array
        items:
          $ref: '#/definitions/recipesvcRecipe'
        title: Array of recipes
    title: Recipes
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: array
        items:
          $ref: '#/definitions/protobufAny'
      message:
        type: string
